name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

concurrency:
    group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: java-no-spring
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '21'
                cache: 'maven'

            - name: Run tests
              run: mvn clean test

    integration-test:
        name: integration-test
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: java-no-spring
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '21'
                cache: 'maven'

            - name: Start Java server
              run: |
                mvn clean package
                java -jar target/*.jar > server.log 2>&1 &
              env:
                PORT: 8080

            - name: Wait for server to start
              run: |
                for i in {1..12}; do
                  if curl -s http://localhost:8080/todos > /dev/null; then
                    echo "Server is up!"
                    exit 0
                  fi
                  echo "Waiting for server..."
                  sleep 1
                done

            - name: Run integration tests
              run: ../scripts/integration-test.sh
              env:
                ENV: dev

            - name: Stop Java server
              run: pkill java