name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-no-spring
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
      - run: mvn clean test

  integration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-no-spring
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
      
      # Build and start server with proper error handling
      - name: Build and start server
        run: |
          mvn clean package
          java -jar target/*.jar &
          echo $! > server.pid
          
          # Wait for server to be ready
          for i in {1..30}; do
            if curl -s http://localhost:8080/todos > /dev/null; then
              echo "Server is ready"
              exit 0
            fi
            sleep 1
          done
          
          # If we get here, server failed to start
          echo "Server failed to start"
          cat server.log
          exit 1
        env:
          PORT: 8080

      # Run tests
      - name: Run integration tests
        run: ../scripts/integration-test.sh
        env:
          ENV: dev

      # Ensure server is stopped
      - name: Cleanup
        if: always()
        run: kill $(cat server.pid) || true