name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-no-spring
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn clean test

  integration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-no-spring
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and start server
        run: |
          mvn clean package
          java -jar target/*.jar > server.log 2>&1 &
          echo $! > server.pid
          for i in {1..30}; do
            if curl -s http://localhost:8080/todos; then
              echo "Server is ready"
              exit 0
            fi
            echo "Waiting for server... attempt $i"
            sleep 2
          done
          echo "Server failed to start"
          cat server.log
          exit 1
      - name: Run integration tests
        run: ../scripts/integration-test.sh
        env:
          ENV: dev
      - name: Cleanup
        if: always()
        run: kill $(cat server.pid) || true