name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: docker build --target build -t my-app-build -f Dockerfile .

  integration-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t my-app-image -f Dockerfile .
      - name: Start server in Docker container
        run: |
          docker run -d --name my-app-container -p 8080:8080 my-app-image
          for i in {1..10}; do
            if curl -s http://localhost:8080/todos > /dev/null; then
              echo "Server is ready"
              exit 0
            fi
            echo "Waiting for server... attempt $i"
            sleep 2
          done
          echo "Server failed to start"
          docker logs my-app-container
          exit 1
      - name: Run integration tests
        run: docker exec my-app-container /app/scripts/integration-test.sh
        env:
          ENV: dev
      - name: Cleanup
        if: always()
        run: docker stop my-app-container && docker rm my-app-container || true