name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

concurrency:
    group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: java-no-spring
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '21'
                cache: 'maven'

            - name: Run tests
              run: mvn clean test

    integration-test:
        name: integration-test
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: java-no-spring
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '21'
                cache: 'maven'

            - name: Start Java server
              run: |
                mvn clean package
                java -jar target/*.jar > server.log 2>&1 &
              env:
                PORT: 8080

            - name: Wait for server to start
              run: |
                timeout=30
                elapsed=0
                while ! curl -s http://localhost:8080/todos > /dev/null; do
                  if [ $elapsed -ge $timeout ]; then
                    echo "Error: Server failed to start within $timeout seconds"
                    cat server.log
                    exit 1
                  fi
                  echo "Waiting for server... ($elapsed/$timeout seconds)"
                  sleep 2
                  elapsed=$((elapsed+2))
                done
                echo "Server is up!"

            - name: Run integration tests
              run: ../scripts/integration-test.sh
              env:
                ENV: dev

            - name: Stop Java server
              run: pkill java