name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Build and test
        working-directory: java-no-spring
        run: mvn clean test

  integration-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Start server
        working-directory: java-no-spring
        run: |
          mvn clean compile exec:java -Dexec.mainClass="com.github.vrnvu.App" &
          for i in {1..30}; do
            if curl -s http://localhost:8080/todos > /dev/null; then
              echo "Server is ready"
              exit 0
            fi
            echo "Waiting for server... attempt $i"
            sleep 2
          done
          echo "Server failed to start"
          exit 1
      - name: Run integration tests
        working-directory: java-no-spring
        run: ../scripts/integration-test.sh
        env:
          ENV: dev